#pragma once

enum XACT_WAVEBANK_SKBX : unsigned int
{
    XACT_WAVEBANK_SKBX_BGM_TITLESELECT = 0,
    XACT_WAVEBANK_SKBX_BGM_PLAY = 1,
    XACT_WAVEBANK_SKBX_BGM_RESULT = 2,
    XACT_WAVEBANK_SKBX_SE_COINGETTER = 3,
    XACT_WAVEBANK_SKBX_SE_SELECT = 4,
    XACT_WAVEBANK_SKBX_SE_WIND = 5,
    XACT_WAVEBANK_SKBX_SE_CLEAR = 6,
    XACT_WAVEBANK_SKBX_SE_DECISION = 7,
};

#define XACT_WAVEBANK_SKBX_ENTRY_COUNT 8
